# Generated by Django 6.0.2 on 2026-02-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='username',
            options={'verbose_name': 'Name', 'verbose_name_plural': 'Names'},
        ),
        migrations.AlterField(
            model_name='username',
            name='name',
            field=models.CharField(max_length=100, verbose_name='User name'),
        ),
    ]
